/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.courseWork2.view;

import edu.ijse.courseWork2.controller.BookController;
import edu.ijse.courseWork2.controller.MemberController;
import edu.ijse.courseWork2.controller.ReturnBookController;
import edu.ijse.courseWork2.controller.TransactionController;
import edu.ijse.courseWork2.dto.TransactionDto;
import edu.ijse.courseWork2.dto.ReturnBookDto;
import edu.ijse.courseWork2.dto.MemberDto;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isuru Manchanayake
 */
public class ReturnBookView extends javax.swing.JFrame {
    private TransactionController transactionController;
    private MemberController memberController;
    private BookController bookController;
    private ReturnBookController returnBookController;

    /**
     * Creates new form ReturnBookView
     */
    public ReturnBookView() {
        initComponents();
        transactionController = new TransactionController();
        memberController = new MemberController();
        bookController = new BookController();
        returnBookController = new ReturnBookController();
        toDay();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLReturnBook = new javax.swing.JLabel();
        jLTranId = new javax.swing.JLabel();
        jTxtTranId = new javax.swing.JTextField();
        jBtnClick = new javax.swing.JButton();
        jLRetrnDate = new javax.swing.JLabel();
        jTxtReturnDate = new javax.swing.JTextField();
        jTxtFine = new javax.swing.JTextField();
        jLFine = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblReturn = new javax.swing.JTable();
        jTxtBorrrowDate = new javax.swing.JTextField();
        jLBorrowDate = new javax.swing.JLabel();
        jTxtDueDate = new javax.swing.JTextField();
        jLDueDate = new javax.swing.JLabel();
        jTxtTranDetail = new javax.swing.JTextField();
        jBtnDelete = new javax.swing.JButton();
        jLBookId = new javax.swing.JLabel();
        jTxtBookId = new javax.swing.JTextField();
        jLQty = new javax.swing.JLabel();
        jTxtQty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Return Book Form");

        jLReturnBook.setBackground(new java.awt.Color(204, 255, 51));
        jLReturnBook.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLReturnBook.setForeground(new java.awt.Color(102, 0, 0));
        jLReturnBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLReturnBook.setText("RETURN BOOK");
        jLReturnBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jLTranId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTranId.setText("Transaction Id");

        jTxtTranId.setBackground(new java.awt.Color(204, 204, 204));

        jBtnClick.setBackground(new java.awt.Color(255, 102, 102));
        jBtnClick.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnClick.setText("Click");
        jBtnClick.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClickActionPerformed(evt);
            }
        });

        jLRetrnDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLRetrnDate.setText("Return Date");

        jTxtReturnDate.setBackground(new java.awt.Color(204, 204, 204));

        jTxtFine.setBackground(new java.awt.Color(204, 204, 204));

        jLFine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLFine.setText("Fine");

        jBtnSave.setBackground(new java.awt.Color(0, 153, 153));
        jBtnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSave.setText("Save");
        jBtnSave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jTblReturn.setBackground(new java.awt.Color(153, 255, 255));
        jTblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblReturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblReturn);

        jTxtBorrrowDate.setBackground(new java.awt.Color(204, 204, 204));

        jLBorrowDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLBorrowDate.setText("Borrow Date");

        jTxtDueDate.setBackground(new java.awt.Color(204, 204, 204));

        jLDueDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLDueDate.setText("Due Date");

        jTxtTranDetail.setBackground(new java.awt.Color(204, 255, 153));

        jBtnDelete.setBackground(new java.awt.Color(153, 153, 0));
        jBtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnDelete.setText("Delete");
        jBtnDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jLBookId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLBookId.setText("Book Id");

        jTxtBookId.setBackground(new java.awt.Color(204, 204, 204));

        jLQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLQty.setText("Qty");

        jTxtQty.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLReturnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLRetrnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLFine, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtFine, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLQty, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLTranId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtTranId))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtBorrrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtTranDetail)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTranId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTranId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTranDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBorrrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRetrnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLQty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClickActionPerformed
        click();
    }//GEN-LAST:event_jBtnClickActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        saveReturn();
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        DeleteReturnDetail();
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jTblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblReturnMouseClicked
        mouseClick();
    }//GEN-LAST:event_jTblReturnMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReturnBookView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClick;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLBookId;
    private javax.swing.JLabel jLBorrowDate;
    private javax.swing.JLabel jLDueDate;
    private javax.swing.JLabel jLFine;
    private javax.swing.JLabel jLQty;
    private javax.swing.JLabel jLRetrnDate;
    private javax.swing.JLabel jLReturnBook;
    private javax.swing.JLabel jLTranId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblReturn;
    private javax.swing.JTextField jTxtBookId;
    private javax.swing.JTextField jTxtBorrrowDate;
    private javax.swing.JTextField jTxtDueDate;
    private javax.swing.JTextField jTxtFine;
    private javax.swing.JTextField jTxtQty;
    private javax.swing.JTextField jTxtReturnDate;
    private javax.swing.JTextField jTxtTranDetail;
    private javax.swing.JTextField jTxtTranId;
    // End of variables declaration//GEN-END:variables

    private void click() {
         try {
          String transactionId = jTxtTranId.getText();
          TransactionDto transactionDto  = transactionController.get(transactionId);
          if(transactionDto != null){
          jTxtBorrrowDate.setText(transactionDto.getBorrowDate());
          jTxtDueDate.setText(transactionDto.getDueDate());
          jTxtTranDetail.setText(transactionDto.getBookId()+" | "+transactionDto.getMemberId());
          jTxtBookId.setText(transactionDto.getBookId());
          jTxtQty.setText(String.valueOf(transactionDto.getNoOfBook()));
          calFine();
          }else{
              jTxtBorrrowDate.setText("Not Found");
              jTxtDueDate.setText("Not Found");
                      
          }
           
      } catch (Exception e) {
          e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error at search Transaction Details");
      }
  }

    private void saveReturn() {
         try {
              ReturnBookDto dto = new ReturnBookDto(
                 jTxtTranId.getText(),
                 jTxtBorrrowDate.getText(),
                 jTxtDueDate.getText(),
                 jTxtReturnDate.getText(),
                 Integer.parseInt(jTxtFine.getText()),
                 jTxtBookId.getText(),
                 Integer.parseInt(jTxtQty.getText())
                      
              );
                      
              
              String resp = returnBookController.save(dto);
              
              JOptionPane.showMessageDialog(this, resp);
              clearForm();
              loadTable();
            
        } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Error at save data");
              clearForm();
        }
    
    }

    private void clearForm() {
         jTxtTranId.setText("");
         jTxtBorrrowDate.setText("");
         jTxtDueDate.setText("");
         jTxtReturnDate.setText("");
         jTxtFine.setText("");
         jTxtBookId.setText("");
         jTxtQty.setText("");
    }

    private void loadTable() {
         try {
            String columns[]={"Transaction ID","Borrow date","Due Date","Return Date","Fine","Book Id","No. of borrow book"};
           DefaultTableModel dtm=new DefaultTableModel(columns,0){
               @Override
              public boolean isCellEditable(int row, int column){
                 return false;
              }
           };
           jTblReturn.setModel(dtm);
           
           ArrayList<ReturnBookDto>returnBookDtos = returnBookController.getAll();
           for(ReturnBookDto dto : returnBookDtos){
             Object[] rowData = {
                 dto.getTransactionId(),
                 dto.getBorrowDate(),
                 dto.getDuedate(),
                 dto.getReturnDate(),
                 dto.getFine(),
                 dto.getBookId(),
                 dto.getQty(),
                 
                 };
             dtm.addRow(rowData);
           }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at loading Data to Return Book table");
        }
    }
    
     private void toDay(){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(new Date());
            jTxtReturnDate.setText(date);
    }
     
    

private void calFine() {
    int fine = 0;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    LocalDate dueDate = LocalDate.parse(jTxtDueDate.getText(), formatter);
    LocalDate returnDate = LocalDate.parse(jTxtReturnDate.getText(), formatter);

    if (returnDate.isAfter(dueDate)) {
        long daysBetween = ChronoUnit.DAYS.between(dueDate, returnDate);
        fine = (int) daysBetween * 2;
    }
    jTxtFine.setText(String.valueOf(fine));
}

    private void DeleteReturnDetail() {
        try {
         String transactionId = jTxtTranId.getText();
         String resp = returnBookController.delete(transactionId);
            System.out.println("Delete");
         JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
         
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error at Cancel Book");
     }
 }

    private void mouseClick() {
         try {
       String transactionId = jTblReturn.getValueAt(jTblReturn.getSelectedRow(), 0).toString();
       ReturnBookDto dto=returnBookController.get(transactionId);
       
       if(dto != null){
          jTxtTranId.setText(dto.getTransactionId());
          jTxtBorrrowDate.setText(dto.getBorrowDate());
          jTxtDueDate.setText(dto.getDuedate());
          jTxtReturnDate.setText(dto.getReturnDate());
          jTxtFine.setText(Integer.toString(dto.getFine()));
          jTxtBookId.setText(dto.getBookId());
          jTxtQty.setText(Integer.toString(dto.getQty()));
          
       }else{
          JOptionPane.showMessageDialog(this, "Return not found");
       }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error at loading ");
     }
 }
}
