/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.courseWork2.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Isuru Manchanayake
 */
public class UserLoginView extends javax.swing.JFrame {
    /**
     * Creates new form UserLoginView
     */
    public UserLoginView() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitle = new javax.swing.JLabel();
        jBtnBook = new javax.swing.JButton();
        jBtnMember = new javax.swing.JButton();
        jBtnBookCategory = new javax.swing.JButton();
        jBtnTransaction = new javax.swing.JButton();
        jBtnReturnBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Login");
        setBackground(new java.awt.Color(255, 255, 153));

        jLTitle.setBackground(new java.awt.Color(204, 204, 204));
        jLTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLTitle.setForeground(new java.awt.Color(102, 0, 0));
        jLTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitle.setText("UNIVERSITY SCIENCE LIBRARY");

        jBtnBook.setBackground(new java.awt.Color(0, 204, 204));
        jBtnBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnBook.setText("BOOK");
        jBtnBook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBookActionPerformed(evt);
            }
        });

        jBtnMember.setBackground(new java.awt.Color(0, 153, 153));
        jBtnMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnMember.setText("MEMBER");
        jBtnMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMemberActionPerformed(evt);
            }
        });

        jBtnBookCategory.setBackground(new java.awt.Color(0, 102, 102));
        jBtnBookCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnBookCategory.setText("BOOK CATEGORY");
        jBtnBookCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBookCategoryActionPerformed(evt);
            }
        });

        jBtnTransaction.setBackground(new java.awt.Color(0, 153, 204));
        jBtnTransaction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnTransaction.setText("TRANSACTION");
        jBtnTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTransactionActionPerformed(evt);
            }
        });

        jBtnReturnBook.setBackground(new java.awt.Color(51, 255, 204));
        jBtnReturnBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnReturnBook.setText("RETURN BOOK");
        jBtnReturnBook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReturnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnTransaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jBtnReturnBook, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jBtnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnBookCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBookCategoryActionPerformed
       openBookCategory();
    }//GEN-LAST:event_jBtnBookCategoryActionPerformed

    private void jBtnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTransactionActionPerformed
        openTransaction();
    }//GEN-LAST:event_jBtnTransactionActionPerformed

    private void jBtnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMemberActionPerformed
        openMember();
    }//GEN-LAST:event_jBtnMemberActionPerformed

    private void jBtnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBookActionPerformed
        openBook();
    }//GEN-LAST:event_jBtnBookActionPerformed

    private void jBtnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReturnBookActionPerformed
        returnBook();
    }//GEN-LAST:event_jBtnReturnBookActionPerformed

    /**
     * @param args the command line arguments
     */
 //   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
 //       java.awt.EventQueue.invokeLater(new Runnable() {
 //           public void run() {
 //               new UserLoginView().setVisible(true);
 //           }
 //       });
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBook;
    private javax.swing.JButton jBtnBookCategory;
    private javax.swing.JButton jBtnMember;
    private javax.swing.JButton jBtnReturnBook;
    private javax.swing.JButton jBtnTransaction;
    private javax.swing.JLabel jLTitle;
    // End of variables declaration//GEN-END:variables

    private void openBookCategory() {
        try {
            new CategoryView().setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error");
        }
        
        
        
    }

    private void openTransaction() {
         try {
            new TransactionView().setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error");
        }
    
}

    private void openMember() {
        try {
            new MemberView().setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error");
        }
  }

    private void openBook() {
        try {
            new BookView().setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error");
        }
    
}

    private void returnBook() {
         try {
            new ReturnBookView().setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error");
        }
    
}
}
